### PR TITLE
Verify encoding issues for Invoke-PBRubrikHello - Issue 21

### LINKED ISSUE #21: Verify encoding issues for Invoke-PBRubrikHello
## Expected Behavior
I expect the function to be dot sourced

## Current Behavior
Currently dot-sourcing fails on Windows PowerShell 5.1:

```
PS C:\Users\Jaap> . C:\temp\rubrik-module-for-poshbot\PoshBot.Rubrik\public\Invoke-PBRubrikHello.ps1
At C:\temp\rubrik-module-for-poshbot\PoshBot.Rubrik\public\Invoke-PBRubrikHello.ps1:14 char:33
+ ... ä½ å¥½ï¼Œæˆ‘æ˜¯ç½—èŒœï¼ä»Šå¤©æˆ‘å°†æ­£å¼è¿è¡Œä¸ºPoshBotæ­å»ºçš„Ru ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'æ˜¯ç½—èŒœï¼ä»Šå¤©æˆ‘å°†æ£å¼è¿è¡Œä¸ºPoshBotæå»ºçš„Rubrikæ¨¡å— 1.0.0.0 ç‰ˆæœ¬ï¼'' in expression
or statement.
At C:\temp\rubrik-module-for-poshbot\PoshBot.Rubrik\public\Invoke-PBRubrikHello.ps1:14 char:33
+             Text = 'ä½ å¥½ï¼Œæˆ‘æ˜¯ç½—èŒœï¼ä»Šå¤©æˆ‘å°†æ­£å¼è¿è¡Œä ...
```

## Possible Solution
Encoding foreign characters as base64 strings instead of Unicode

### PR DESCRIPTION
**Pull request by jaapbrasser**
## Expected Behavior

I expect the function to be dot sourced regardless of the PowerShell version used

## Current Behavior
Currently dot-sourcing fails on Windows PowerShell 5.1:

## Related Issue

Resolve #21 

## Motivation and Context

Module should be cross-platform

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by jaapbrasser** [comment]
Not ready for review, looking into catching Windows PowerShell / PowerShell Core testing in Azure Pipelines

**Comment by rfitzhugh** [comment]
@jaapbrasser - let me know when you're ready for review.

**Comment by jaapbrasser** [comment]
@rfitzhugh Will do, I am looking at updating the pipeline so we can catch these errors going forward! Should be fixed today.

**Comment by jaapbrasser** [comment]
@rfitzhugh Ready for review

**Pull request merged**
